name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: |
          ng build --prod

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/ecommerce-platform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
